name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        # Put your action repo here
        uses: ovcharenko/python-container-action@master

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.myOutput }}" == "Hello world"

      - name: Run this action
        uses: gacts/run-and-post-run@v1
        with:
          run: echo "First"
            "${{ steps.selftest.outputs.myOutput }}"
          post: |
            echo "First post"
            echo "(can run multiply commands)"
            ls -la /tmp \
              /bin /opt

      - name: Post command only
        uses: gacts/run-and-post-run@v1
        with:
          post: echo "Second post"